"""This file was automatically generated by cvsimlib."""

from hamiltonians import MultitoneDrives
import numpy as np

gate_time = 4.2
target_states = [1, 3, 5, 7, 9]
target_phases = [0., 0., 0., 0., 0.]

qubit_T1 = 80
qubit_T2 = 20
cavity_T1 = 567

hilbert_space = (12, 5)

parameters = {
    "drives": None,
    "delta": 30 * 2 * np.pi,
    "cavity_frequency": 3.581e3 * 2 * np.pi,
    "cavity_kerr": 2.2e-3 * 2 * np.pi,
    "disp_shift": 1.44 * 2 * np.pi,
    "disp_shift_corr": 1e-3 * 2 * np.pi,
    "qubit_anharmonicity": 231 * 2 * np.pi,
    "qubit_frequency": 5.523e3 * 2 * np.pi,
    "kappa_1q": 1/qubit_T1,
    "kappa_2q": 1/qubit_T2,
    "kappa_c": 1/cavity_T1,
    "hilbert_space": hilbert_space
}

drives = MultitoneDrives()
drives.add_qubit_drive(0, parameters["qubit_frequency"] - parameters["delta"])
for n in target_states:
    drives.add_cavity_drive(0, parameters["cavity_frequency"] + parameters["delta"] - (n + 1)*parameters['disp_shift'])
parameters["drives"] = drives

arguments = {
}
